### ISSUE TITLE
Resources page has misaligned worksheet links

### ISSUE THREAD

**Issue by smartspot2** [csmberkeley/csm_web#520]
The "worksheetse" column has some weird formatting, which causes links to be misaligned. See below for an example:
![Image](https://github.com/user-attachments/assets/fc513d2b-c5be-422b-b08f-f10eab39929e)

This is likely due to the `grid-template-columns` setting in the CSS in `resource_aggregation.scss`:
```scss
.resource-worksheet {
  display: grid;
  grid-template-columns: repeat(3, 1fr) 20px;
  column-gap: 10px;
}
```
